name: File Format Check for Treasury, Salary, Income proposals

on:
  pull_request:
    types: [opened, synchronize, reopened, edited, labeled, unlabeled]

jobs:
  check_changes:
    if: contains(github.event.pull_request.labels.*.name, 'Treasury proposal') || contains(github.event.pull_request.labels.*.name, 'Salary proposal') || contains(github.event.pull_request.labels.*.name, 'Income proposal')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_TOKEN }}

      - name: Get label names
        id: get_labels
        run: |
          labels=$(jq -r ".pull_request.labels | length" "$GITHUB_EVENT_PATH")
          pr_labels=$(jq -r ".pull_request.labels[].name" "$GITHUB_EVENT_PATH")
          echo "Labels: $pr_labels"
          echo "::set-output name=LABELS::$pr_labels"

      - name: Determine directory based on labels
        id: determine_directory
        run: |
          label_names="${{ steps.get_labels.outputs.LABELS }}"
          if [[ "$label_names" == *"Treasury proposal"* ]]; then
            directory="finance/treasury_proposals"
          elif [[ "$label_names" == *"Income proposal"* ]]; then
            directory="finance/income_proposals"
          elif [[ "$label_names" == *"Salary proposal"* ]]; then
            directory="finance/salary_proposals"
          fi
          echo "Directory: $directory"
          echo "::set-output name=DIRECTORY::$directory"

      - name: Get changed files in pull request
        id: get_changed_files
        run: |
          directory="${{ steps.determine_directory.outputs.DIRECTORY }}"
          changed_files=$(curl -s -H "Authorization: token ${{ secrets.GH_TOKEN }}" \
          -X GET "${{ github.api_url }}/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/files" \
          | jq -r --arg directory "$directory" '.[] | select(.filename | contains($directory)) | .filename')
          echo "::set-output name=CHANGED_FILES::$changed_files"

      - name: Check for Proposal Changes
        run: |
          changed_files="${{ steps.get_changed_files.outputs.CHANGED_FILES }}"
          if [ -z "$changed_files" ]; then
            echo "No changes made to the $directory directory."
            exit 1
          else
            echo "Changes detected in the $directory directory."
            current_month_year=$(date +"%m_%Y")
            while read -r file; do
              filename=$(basename "$file")
              echo "File name: $filename"
              # Extract month, year, and title from the filename
              file_month_year=$(echo "$filename" | cut -d'_' -f1,2)
              file_title=$(echo "$filename" | cut -d'_' -f3 | cut -d'.' -f1)
              # Check if the file name format is correct
              if [[ ! "$filename" =~ ^[0-9]{2}_[0-9]{4}_[a-zA-Z0-9_]{1,11}\.md$ ]]; then
                echo "Error: Incorrect file name format in $filename."
                exit 1
              fi
              # Check if the month and year match the current month and year
              if [ "$file_month_year" != "$current_month_year" ]; then
                echo "Error: File $filename does not match the current month and year."
                exit 1
              fi
              # Check if the title length is within 12 characters
              if [ ${#file_title} -gt 12 ]; then
                echo "Error: Title in $filename exceeds 12 characters."
                exit 1
              fi
            done <<< "$changed_files"
          fi
