name: Check Proposal Changes

on:
  pull_request:
    types: [opened, synchronize, reopened, edited, labeled, unlabeled]

jobs:
  check_changes:
    if: |
      contains(github.event.pull_request.labels.*.name, 'Calendar proposal') ||
      contains(github.event.pull_request.labels.*.name, 'OKR proposal')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_TOKEN }}

      - name: Get changed files in pull request
        id: get_changed_files
        run: |
          changed_files=$(curl -s -H "Authorization: token ${{ secrets.GH_TOKEN }}" \
          -X GET ${{ github.api_url }}/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/files \
          | jq -r '.[] | .filename')
          echo "::set-output name=CHANGED_FILES::$changed_files"

      - name: Check for changes based on labels
        run: |
          if [ "${{ github.event_name }}" == "pull_request" ]; then
            case "${{ steps.get_changed_files.outputs.CHANGED_FILES }}" in
              *"calender"*)
                echo "Changes detected in Calendar proposal folder."
                while read -r file; do
                  filename=$(basename "$file")
                  echo "$filename"
                done <<< "${{ steps.get_changed_files.outputs.CHANGED_FILES }}"
                ;;
              *"monthly_OKR"*)
                echo "Changes detected in OKR proposal folder."
                while read -r file; do
                  filename=$(basename "$file")
                  echo "$filename"
                done <<< "${{ steps.get_changed_files.outputs.CHANGED_FILES }}"
                ;;
              *)
                echo "No relevant changes detected."
                exit 1
                ;;
            esac
          fi
