name: File Format Check

on:
  pull_request:
    types: [opened, synchronize, reopened, edited, labeled, unlabeled]

jobs:
  check_changes:
    if: contains(github.event.pull_request.labels.*.name, 'Calendar proposal') || contains(github.event.pull_request.labels.*.name, 'OKR proposal')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_TOKEN }}

      - name: Get changed files in pull request
        id: get_changed_files
        run: |
          label_name=$(echo "${{ github.event.pull_request.labels.*.name }}" | tr -d '\n')
          if [ "$label_name" == "Calendar proposal" ]; then
            directory="calender"
          elif [ "$label_name" == "OKR proposal" ]; then
            directory="monthly_OKR"
          fi
          changed_files=$(curl -s -H "Authorization: token ${{ secrets.GH_TOKEN }}" \
          -X GET ${{ github.api_url }}/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/files \
          | jq -r '.[] | select(.filename | contains("'"$directory"'")) | .filename')
          echo "::set-output name=CHANGED_FILES::$changed_files"

      - name: Check for Proposal Changes
        run: |
          directory="${{ steps.get_changed_files.outputs.CHANGED_FILES }}"
          if [ -z "$directory" ]; then
            echo "No changes made to the $directory directory."
            exit 1
          else
            echo "Changes detected in the $directory directory."
            while read -r file; do
              filename=$(basename "$file")
              echo "$filename"
            done <<< "$directory"
          fi
