name: Check Quarterly report changes

on:
  pull_request:
    types: [opened, synchronize, reopened, edited, labeled, unlabeled]

jobs:
  check_changes:
    if: contains(github.event.pull_request.labels.*.name, 'Quarterly Reports')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_TOKEN }}

      - name: Get changed files in pull request
        id: get_changed_files
        run: |
          changed_files=$(curl -s -H "Authorization: token ${{ secrets.GH_TOKEN }}" \
          -X GET ${{ github.api_url }}/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/files \
          | jq -r '.[] | select(.filename | contains("quarterly_reports")) | .filename')
          echo "::set-output name=CHANGED_FILES::$changed_files"

      - name: Check for Quarterly Reports changes
        run: |
          if [ -z "${{ steps.get_changed_files.outputs.CHANGED_FILES }}" ]; then
            echo "No changes made to Quarterly Reports folder."
          else
            echo "Changes detected in Quarterly Reports folder."
            echo "${{ steps.get_changed_files.outputs.CHANGED_FILES }}"
          fi
